### ISSUE TITLE
Support for _vendor entries in manifest.json

### ISSUE THREAD

**Issue by cachitas** [MrBin99/django-vite#1]
Thank you for putting this together for the Django community. I have been playing with it and noticed  an issue.

I have a vendor entry in the manifest generated by `vite build` due to a `import 'alpinejs'` line in my `project.js` entry.
```json
{
  "js/project.js": {
    "file": "assets/project.3d59ab7e.js",
    "src": "js/project.js",
    "isEntry": true,
    "imports": [
      "_vendor.4f4cfc99.js"
    ],
    "css": [
      "assets/project.4db221d9.css"
    ]
  },
  "_vendor.4f4cfc99.js": {
    "file": "assets/vendor.4f4cfc99.js"
  }
}
```

I then inject the built scripts in my template like
```html
{% vite_asset 'js/project.js' %}
{% vite_asset '_vendor.4f4cfc99.js' %}
```
and everything works fine. But that second line being required with a name we only know after building the assets looks like a pitfall.

Is there a better approach to handle these cases?
Would it make sense to have a dedicated `templatetag` to catch all these `"_vendor.*"` entries?
Or could it be handled the same way imported css is by looking for an `imports` key?

**Comment by MrBin99** [comment]
Hello, and first of all thank you.

I think, the solution is to treat this problem like for CSS : not adding an tag but automatically generate all script
tags of dependencies before the integration of the "main" script tag.
Like this :
```
{% vite_asset 'js/project.js' %}
```

Generate in production this :
```html
<link rel="stylesheet" href="assets/project.4db221d9.css"/>
<script src="assets/vendor.4f4cfc99.js"></script>
<script src="assets/project.3d59ab7e.js"></script>
```

What do you think ?

**Comment by cachitas** [comment]
Yes that looks reasonable.

Let me know if you have time to tackle this or if you need me to draft a PR.
I would make it exactly like you have for css.

**Comment by MrBin99** [comment]
I will try to do it ASAP. Maybe this weekend during my spare time.

Thanks.
