### ISSUE TITLE
Handling manifest.json and other Files on S3/Cloud Storage or CDN for production

### ISSUE THREAD

**Issue by shunMB** [MrBin99/django-vite#106]
How to use when manifest.json and other files are on S3 or Cloud storage(or other CDN)?

django-vite expects manifest.json is on local environment, and bring it.
But in my environment, manifest.json and other static files produced by vite are on Cloud Storage.

With setting like below
```
DJANGO_VITE_MANIFEST_PATH = STATIC_ROOT + "/manifest.json":
```

I get error, although the file exists there and includes the key "src/main.js". As you know, it works fine in dev env.
```
RuntimeError: Cannot find src/main.js in Vite manifest at https://my-cloud-storage-bucket/manifest.json
```

What is the best practice in this situations? Downloading manifest.json in local before using takes some redirects and delay. 
Also, similar discussions here: #20 and #44

**Comment by MrBin99** [comment]
The manifest.json file needs to be read in all cases to generates URLs to your assets.
I think putting it with your Python code makes sense, to not call the network to read the file on S3 or in any other service
as reading it on the disk is much faster (the file is read when Django starts up and is cached in memory).
Then use the Django static file system to prefix your assets URLs with the domain to your cloud storage.
