### ISSUE TITLE
Feature request: Support for @vitejs/plugin-legacy

### ISSUE THREAD

**Issue by mixxorz** [MrBin99/django-vite#11]
[@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) adds support for legacy browsers.

It would be great if django-vite could render the legacy bundles generated by the plugin.

**Comment by mixxorz** [comment]
Thanks for the speedy response!

I was thinking we could add a new tag: `vite_legacy_asset`. It works the same way as `vite_asset`, except it renders the legacy chunks instead of the "normal" chunks.

This idea is borrowed from [`vite-ruby`](https://vite-ruby.netlify.app/guide/plugin-legacy.html)

**Comment by MrBin99** [comment]
Ok I see.

I will implement this ASAP, thanks.

**Comment by MrBin99** [comment]
Hi,
I just released a new version supporting `@vitejs/plugin-legacy`.
Tell me what do you think.

Thanks !
