### ISSUE TITLE
Configuration setting DJANGO_VITE_ASSETS_PATH removed?

### ISSUE THREAD

**Issue by danielniccoli** [MrBin99/django-vite#110]
Commit 8fe9b3e3446f1704afb03eecdb96d6e39f971970 removed `DJANGO_VITE_ASSETS_PATH` from `README.md` without its substitute. Is the setting gone, or was it forgotten to be added to the readme?

**Comment by Niicck** [comment]
The setting is gone, you no longer need it. More details are in the v3 PR: https://github.com/MrBin99/django-vite/pull/92

**Comment by danielniccoli** [comment]
Thanks.
