### ISSUE TITLE
New hash pattern in Rollup 4

### ISSUE THREAD

**Issue by petrprikryl** [MrBin99/django-vite#114]
Vite 5 came with Rollup 4 which introduced new hash syntax (hex => base64). I think this should be noted in README.md:
https://github.com/MrBin99/django-vite/blob/66fce41b8eaaea97ff59e070c4ccce961dd6efb9/README.md#L377

New regex proposal: `^.+[\.-][0-9a-zA-Z_-]{8,12}\..+$`

https://github.com/rollup/rollup/pull/5155
https://github.com/rollup/rollup/issues/4803

**Comment by Niicck** [comment]
Closed by: https://github.com/MrBin99/django-vite/pull/130
