### ISSUE TITLE
@vitejs/plugin-react can't detect preamble

### ISSUE THREAD

**Issue by paveu** [MrBin99/django-vite#119]
does anyone encounter follwing error while running vite dev mode through django-vite

```Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong```

I'm not sure if it's related to the django-vite package i think it's not, but maybe someone seen it in the past

**Comment by MrBin99** [comment]
I think you did not inject React specific JS in the page to enable HMR, please check :
- https://github.com/vitejs/vite/issues/1984
- `vite_react_refresh` : https://github.com/MrBin99/django-vite#dev-mode

**Comment by paveu** [comment]
@MrBin99 thanks, it's fixed by applyinng snippet from https://github.com/MrBin99/django-vite/issues/89 , django-csp was blocking @vitejs/plugin-react to start up. Can we merge https://github.com/MrBin99/django-vite/pull/94 i think it would resolve my problem, i could just pass ```request.csp_nonce```

**Comment by MrBin99** [comment]
This PR has conflicts that need to be resolved before merging.

**Comment by Niicck** [comment]
I'm working on updating that PR 👍

**Comment by Niicck** [comment]
This has been added to v3.0.3
