### ISSUE TITLE
Suggestion: Allow CSS and JS files to be rendered separately

### ISSUE THREAD

**Issue by mixxorz** [MrBin99/django-vite#12]
By default, `vite_asset` renders both JS and CSS files in the same place. It would be great if we had an option to only render JS or CSS files. This would be useful if I wanted to render CSS `link src` tags in `<head>` but I wanted JS files to appear at the bottom of `<body>`.

**Comment by MrBin99** [comment]
Yes, but `django_vite` adds the `async` and `defer` attributes.
So these attributes tells the browser to load the script asynchronously and execute it when the page is loaded.
It's the same behaviour as puting your script at the bottom of the `<body>`. It's just the modern way to do it.
