### ISSUE TITLE
Django requesting static assets without the static url path

### ISSUE THREAD

**Issue by shivaam** [MrBin99/django-vite#121]
In my djanog app, Django server is requesting assets from 
`http://localhost:5173/js/apps/home.ts` instead of `http://localhost:5173/static/js/apps/home.ts` even though my STATIC_URL is set correctly. Are there any settings or steps I am missing?

Here is my django settings. 
```
# STATIC
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(BASE_DIR / "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [
    str(APPS_DIR / "static"),
    str(APPS_DIR / "static" / "vite_assets_dist")
]
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


DJANGO_VITE = {
    "default": {
        "dev_mode": True
    }
}

```

**Comment by MrBin99** [comment]
You are in dev mode, Django does not serve files in dev mode this is the Vite internal server who does it as he will provide you hot-reloading.
I think your missing to specify your `STATIC_URL` as the `base` of Vite server, check this https://github.com/MrBin99/django-vite#vitejs

**Comment by shivaam** [comment]
Figured out the issue. The problem is this 

```
{% vite_asset '/js/apps/home.js' %}
```

I have a `/` in front of js which was making it an absolute path. After I removed it the django server started requesting file 
`http://localhost:5173/static/js/apps/home.ts`
