### ISSUE TITLE
Additional attributes on `<link rel="stylesheet">` tag

### ISSUE THREAD

**Issue by KyeRussell** [MrBin99/django-vite#140]
I'm very new to this project so please correct me if I'm wrong, but it seems to me that there's no way for me to ask `{% vite_asset %}` to put, say, `media="print"` on the `<link rel="stylesheet" ...>` it generates for a given asset.

I've suboptimally worked around this using `{% vite_asset_url %}` for the time being.

I'll probably take a look at submitting a PR for this a bit later, however it looks quite difficult to accomplish whilst maintaining `{% vite_asset %}`'s current API.

**Comment by Niicck** [comment]
Yep, you're right. Currently we can only assign attributes to the js script tag, not the css stylesheet link. You're also correct that adding this feature would require an update to the API.

I think to get this to work, we'd want to do something like django-webpack-loader where you can split out the bundles of 'css' and 'js' and assign attributes to each one distinctly: https://github.com/django-webpack/django-webpack-loader?tab=readme-ov-file#rendering-by-file-extension

Take a look at the TagGenerator to get an idea of how attribute assignment is currently done. You're welcome to submit a PR.

**Comment by KyeRussell** [comment]
Heh. I'm actually migrating over from Webpack and `django-webpack-loader`! Cheers 👍
