### ISSUE TITLE
How to watch django template changes?

### ISSUE THREAD

**Issue by jet10000** [MrBin99/django-vite#17]
How to watch django template changes and refresh pages?

**Comment by MrBin99** [comment]
Hi,

You need to create an ViteJS plugin to do that. You can find more informations here [https://vitejs.dev/guide/api-plugin.html](https://vitejs.dev/guide/api-plugin.html).

**Comment by MrBin99** [comment]
As your issue is not related to Django Vite but on ViteJS directly, I close your issue.
