### ISSUE TITLE
Love this library but typo in ReadMe

### ISSUE THREAD

**Issue by ihelmer07** [MrBin99/django-vite#18]
I *LOVE* this library. THANK YOU very much - it streamlined the heck out of my build/development process (31+ apps!) and I really appreciate you taking the time to make it.
So 99% of this issue is to say thank you.

BUT I _think_ there's a typo on line 165 of the README: [link](https://github.com/MrBin99/django-vite/blob/0abd12f484a72157fe05cf150e8fd45b3489c3e9/README.md?plain=1#L165)
```
  `DJANGO_VITE_ASSETS_PATH`. But if you are in production (`DEBUG` is true)
```
shouldn't that be `DEBUG` is false?

**Comment by MrBin99** [comment]
Many thanks !

Yep you are right, there is a typo, I will fix it as soon as I find time to do it 😄
