### ISSUE TITLE
Production Build Not working

### ISSUE THREAD

**Issue by ihelmer07** [MrBin99/django-vite#19]
When adding debug = false annd DJANGO_VITE_DEV_MODE = false, the resulting html has incorrect attributes (`type=module`, `async`, `defer`)

**Steps to recreate**
clone the `https://github.com/MrBin99/django-vite-example`
run:
```
yarn
pip install django django-vite
```

In `settings.py`:
Set Debug = False (which turns DJANGO_VITE_DEV_MODE = False)

then run:
`yarn prod`
then run:
`python manage.py collectstatic`
then run:
`python manage.py runserver`
the console shows two errors:
![image](https://user-images.githubusercontent.com/14080785/144762607-daeadaf8-4018-454d-a5a4-b5cdf7376d87.png)

The resulting html source is:
![image](https://user-images.githubusercontent.com/14080785/144762572-5ed692c2-c3a2-4f91-b0f0-f6aedcfe3f20.png)

which shows:
1. the css is getting a mime/type error.
2. js is 404, and has `type=module`, `async` and `defer`.

I don't think this is expected behavior per the docs:
![image](https://user-images.githubusercontent.com/14080785/144762781-db829df4-b9ec-4bed-b0a8-5e0a47025222.png)

**Comment by MrBin99** [comment]
I've you done `python manage.py collectstatic` ?

**Comment by ihelmer07** [comment]
Yes I did run `python manage.py collectstatic`

**Comment by ihelmer07** [comment]
Found the issue:
One needs to install [WhiteNoise](http://whitenoise.evans.io/en/stable/index.html) serve the static files when `Debug=False`.

I love this project so I'm going to throw in a MR for outlining the set up steps for the example if you're okay with that.

**Comment by MrBin99** [comment]
I don't understand why you want to put this inside the doc. It's a thing you maybe have to do in your environment.
I think it may be useful for a minority of people and for beginner it will be confusing.
Personnaly I serve static files with Nginx and the default Django static files system in production and well configured it works like a charm.

What do you think of maybe, put your doc inside another .md file not inside the root one, and juste put a simple
link to it in the root one ?
(We can continue this conversion in your PR if you want).
