### ISSUE TITLE
Proposal: Add DJANGO_VITE_ASSETS_SUBDIRECTORY

### ISSUE THREAD

**Issue by gnuletik** [MrBin99/django-vite#21]
Hi !

## Current issue

I would like to build my vite assets inside a static's subdirectory.
For example with (`build.outDir: '../static/build/'`) : 
- `app/static/build/main.js`
- `app/static/build/_vendor.c8732.js`
etc...

This architecture would avoid conflicts when sharing static directory with other static files.

It does not seems possible at the moment because assets are inserted from the STATIC_URL only: https://github.com/MrBin99/django-vite/blob/116f61f17ce4622d8e2f83c0bae9a8dbf014a31e/django_vite/templatetags/django_vite.py

## Implementation

Add a new configuration in django settings.py : `DJANGO_VITE_ASSETS_SUBDIRECTORY`.

e.g.
```python
DJANGO_VITE_ASSETS_SUBDIRECTORY = "build"
```

If this variable is defined, assets path would be defined as 
```python
urljoin(
    settings.STATIC_URL,
    settings.DJANGO_VITE_ASSETS_SUBDIRECTORY,
    manifest_entry["file"]
)
````

Would you approve such a PR? I can implement it.
If not, would you have an alternative solution for such a static files architecture?

Thanks!

**Comment by gnuletik** [comment]
Calling it `DJANGO_VITE_STATIC_PREFIX` may be closer to django prefix option.
https://docs.djangoproject.com/en/4.0/ref/settings/#prefixes-optional

**Comment by MrBin99** [comment]
Hi,

Of course I accept PR. Feel free to implement it.

I agree with you to call it `DJANGO_VITE_STATIC_PREFIX`. But by default, I think you need to set it to `False` or empty string and
do some conditions. I don't know how `urljoin` behave with empty strings or booleans.
