### ISSUE TITLE
Script tag shouldn’t have defer, possibly nor async

### ISSUE THREAD

**Issue by batisteo** [MrBin99/django-vite#24]
The `defer` and `async` are added to the script tag:
```html
<script type="module" async="" defer="" src="/static/app.f0505013.js"></script>
```

However, the `defer` attribute is implied by browsers that support `type="module"`, so it shouldn’t be added.

Regarding `async`, it seems it might block the parsing of the DOM to execute the code as soon as possible, out of order.  
IMHO it would be better to remove it, or leave the lib user to add it.

Resource: https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6

**Comment by trepmag** [comment]
Also README.md stat the following:
> In development mode, all scripts are marked as async and defer.

Wondering why scripts inclusions would need to behave differently btw development an production; Is it a _ViteJS HMR client_ requirement?

I agree, the lib user should be able to setup this as he required to...

**Comment by batisteo** [comment]
My point is not that development and production should be different.  
It is that when using `type="module"`, the attribute `defer` is redundant thus shouldn’t be used, because it is the way web browsers implement it.  
Also, `async` might be counter-productive.

**Comment by MrBin99** [comment]
The `type="module"` should always be present no ? Vite will always build as module.
I agree with you with to remove `defer` but let `async` and let the user change it.

Wan you maybe do a PR in this direction ?

**Comment by trepmag** [comment]
Hello, for info, with the patch [9402410](https://github.com/trepmag/django-vite/commit/9402410544c92e82f542e728be626da3613271a8) and the template tag bellow the script tag can be inserted by specifying any attribute the user needs; e.g.:
```
{% theme_vite_asset 'stuff/static/js/main.js' type='module' %}
```

Template tag:
```py
@register.simple_tag
@mark_safe
def theme_vite_asset(path, *args, **kwargs):
    scripts_attrs = kwargs
    return DjangoViteAssetLoader.instance().generate_vite_asset(
        path, scripts_attrs=scripts_attrs
    )
```

**Comment by MrBin99** [comment]
Hi, i'm currently working on a version 2.0 of Django Vite, it will make easier to customize async, defer and custom attributes.
It will also support pathlib.Path sor settings.

Stay tune.

**Comment by batisteo** [comment]
I think it should be nice to stick as much as possible to the Vite defaults:

> dev

```html
<html>
	<head>
		<script type="module" src="/@vite/client"></script>
	</head>
	<body>
	    <div id="app"></div>
		<script type="module" src="/main.js"></script>
	</body>
</html>
```

> build

```html
<html>
	<head>
	    <script type="module" crossorigin src="/assets/index.f72635f1.js"></script>
	</head>
	<body>
		<!-- ... -->
	</body>
</html>
```

**Comment by MrBin99** [comment]
I think it depends on what you are doing in your scripts and I think in most of the case you want to manipulate the DOM (with Vue, React or pure JS).
So i will make `defer` true by default but not `async`. Then by tag you will be able to change that and add more attributes.

But you're right, I should add a `crossorigin` attribute by default.

**Comment by MrBin99** [comment]
I pushed my WIP update : what do you think : https://github.com/MrBin99/django-vite/tree/2.0

**Comment by batisteo** [comment]
I’m afraid to repeat myself:
> However, the defer attribute is implied by browsers that support type="module", so it shouldn’t be added.

**Comment by batisteo** [comment]
- There is no need to use the defer attribute (see [<script> attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes)) when loading a module script; modules are deferred automatically.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts

**Comment by MrBin99** [comment]
Sorry I'm an idiot 😅
I forgot that we are talking about modules ...
I'll fix that.

**Comment by MrBin99** [comment]
Just update the 2.0 branch, thanks for your feedback !

**Comment by MrBin99** [comment]
Fixed in version `2.x`
