### ISSUE TITLE
CSS "flickers" on every page load

### ISSUE THREAD

**Issue by akloster** [MrBin99/django-vite#25]
I set up vite and django-vite with custom bootstrap compilation. Now whenever I navigate or reload the page, the content is first shown without the CSS applied. It's only very short, milliseconds at best, but quite annoying. Probably not a problem in production, since the assets are loaded from the same host or at least with proper cache headers...

I also set up a reverse proxy to serve the vite and django dev server from the same port, that didn't help either...

**Comment by akloster** [comment]
I managed a workaround by setting display:none on the body tag in my template markup, then setting it to block again in the loaded css. I'll probably deactivate that for production mode.

**Comment by MrBin99** [comment]
It is normal in development mode because CSS is loaded in JS to handle hot reloading.
In production, Vite will generate plain CSS files that you can import with django-vite.
