### ISSUE TITLE
How to load CSS with relative file imports

### ISSUE THREAD

**Issue by qkjosh** [MrBin99/django-vite#27]
I'm trying to import some CSS that's in a package ([roboto-fontface](https://www.npmjs.com/package/roboto-fontface)) in `node_modules`.
```
// main.js
import 'roboto-fontface/css/roboto/roboto-fontface.css';
```
That CSS file links to fonts whose files are in the same npm package, up two directories.
```
// roboto-fontface.css
@font-face {
    font-family: 'Roboto';
    src: url('../../fonts/roboto/Roboto-Thin.woff2') format('woff2'), url('../../fonts/roboto/Roboto-Thin.woff') format('woff');
    font-weight: 100;
    font-style: normal;
}
```
When I try to run Vite, I get a server 500 error trying to access the font file, because the files are outside the `static/dist` folder:
```
django.core.exceptions.SuspiciousFileOperation: The joined path (G:\redacted\django-vite-example-master\node_modules\roboto-fontface\fonts\roboto\Roboto-Thin.woff) is located outside of the base path component (G:\redacted\django-vite-example-master\static\dist)
```
The URL to the font is also odd...
```
http://127.0.0.1:8000/static/@fs/G:/redacted/django-vite-example-master/node_modules/roboto-fontface/fonts/roboto/Roboto-Bold.woff
```

Should I be handling CSS file imports differently?

**Comment by MrBin99** [comment]
What I typically do is download all fonts in my project next to my CSS and JS files (in a folder folder called `fonts`) to avoid this type of error (and I use this tool [https://transfonter.org](https://transfonter.org) to ensure compatibility with all formats).
Or you can use an `@import` of the Google Fonts CDN in your CSS file.

**Comment by quroom** [comment]
Mrbin99's opinion is truly perfect. I solved the problem with his mention.
```
1. Move module code to your staticfile folder
2. Add link tag like below
    <link rel="stylesheet" href="/static/material-icons/material-icons.css" />
```
I solved same problem.
Thanks a lot!

**Comment by danielniccoli** [comment]
Add `server.origin` to your `vite.config.js`:

```js
export default defineConfig({
    server: {
        origin: 'http://localhost:5173',
    },
})

You must use the exact same URL that is displayed when you start Vite. You can't even use `127.0.0.1` if vite runs on `localhost` or vice versa!

![grafik](https://github.com/MrBin99/django-vite/assets/2971735/e8aea78f-6114-4161-8df8-38edd8d760b9)

But this will work!
