### ISSUE TITLE
Support pathlib.Path in configuration

### ISSUE THREAD

**Issue by joahim** [MrBin99/django-vite#28]
Currently `django-vite` configuration settings (e.g. `DJANGO_VITE_ASSETS_PATH`, `DJANGO_VITE_MANIFEST_PATH`) must be strings or else the following error is thrown:

```
  ...
  File "/usr/local/lib/python3.9/site-packages/django_vite/templatetags/django_vite.py", line 51, in <module>
    DJANGO_VITE_ASSETS_PATH if settings.DEBUG else urljoin(
  File "/usr/local/lib/python3.9/urllib/parse.py", line 530, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/usr/local/lib/python3.9/urllib/parse.py", line 125, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

It also forces the `STATIC_ROOT` to be os type `string`.

It would be a convenient if the `django-vite` configuration would be able to process `pathlib.Path` as well strings.

**Comment by MrBin99** [comment]
Yeah it will be a good improvment.
I'll mark it in my TODOs.

For now you can just wrap your paths. with `str()`.
