### ISSUE TITLE
Using the module/nomodule pattern with legacy plugin

### ISSUE THREAD

**Issue by tomodwyer** [MrBin99/django-vite#3]
Firstly, thanks for this project - it has been a massive help getting a project I'm working on to use Vite.

I'm struggling with one part, which is trying to use the `@vitejs/plugin-legacy` plugin, and the [module/nomodule pattern](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) for loading modern JS.

I've set up the `<head>` of my `base.html` to use the following tags:

```jinja
{% vite_hmr_client %}
{% vite_asset 'assets/scripts/main.js' %}
{% vite_asset "vite/legacy-polyfills" %}
{% vite_asset "assets/scripts/main-legacy.js" %}
```

Which adds all the relevant tags to the output HTML:

```html
<link rel="stylesheet" href="/static/assets/main.js.d1db5761.css">
<script type="module" async="" defer="" src="/static/assets/vendor.f0e51446.js"></script>
<script type="module" async="" defer="" src="/static/assets/main.js.d4eb80fe.js"></script>
<script type="module" async="" defer="" src="/static/assets/polyfills-legacy.f77aab1e.js"></script>
<script type="module" async="" defer="" src="/static/assets/main.js-legacy.312d2a60.js"></script>
```

I want to be able to remove the `type` attribute from the legacy JS files, and instead add `nomodule`, however when I try to add this in my template, I get an error.

`base.html`:

```jinja
{% vite_asset "vite/legacy-polyfills" scripts_attrs={'nomodule', ''} %}
```

Error in console:

```sh
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{'nomodule',' from '{'nomodule','
```

Am I doing something wrong here?

**Comment by MrBin99** [comment]
Hi and thanks !

You can't use directly a dictionary value into a Django template. You need to have a context variable on your view like so :

In your Python code :
```python
def my_view(request):
    scripts_attrs_legacy = {'nomodule': ''}

    return render(request, 'my_template.html', {
        'scripts_attrs_legacy': scripts_attrs_legacy
    })
```

And in your HTML template :

```html
{% vite_asset "vite/legacy-polyfills" scripts_attrs=scripts_attrs_legacy %}
```

Maybe you can use a middleware to add this context variable to all views : [https://www.valentinog.com/blog/django-middleware/](https://www.valentinog.com/blog/django-middleware/)

**Comment by tomodwyer** [comment]
Brilliant thanks, that all makes sense. I'm a front-end developer so just assumed you could add that dictionary straight into the template.

I'll close the issue 👍
