### ISSUE TITLE
Vite's hashlength and Whitenoise cache-control

### ISSUE THREAD

**Issue by gone** [MrBin99/django-vite#30]
I his this today and I'm not sure what the best solution is (although I think it might be a documentation update)

When I generate the vite assets for my project I move them into a static source folder, and then collect static them into the final static destination.  So I generate from vite "assets/main.8759e14c.css", and then collectstatic picks that up and moves it to "assets/main.8759e14c.85ba8b404fb8.css". The version served is the vite manifest vesrion, so only the first hash. 

I can also generate the files directly into my static folder, so they're not included into the collectstatic. Now I only have one copy of assets and that seems better. I think that's your intended way of using the library.

The issues is that I'm using whitenoise to serve assets - Whitenoise wants to set a cache-control header depending on the file name, and the logic it uses to determine if the file is long lived is documented here: http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_IMMUTABLE_FILE_TEST

Vite generates a hash of 8 chars - not the 12 that django generates, so whitenoise thinks it's a mutable file. you can work around this by adding:

```
import re
# Vite generates files with 8 hash digits
# http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_IMMUTABLE_FILE_TEST
def immutable_file_test(path, url):
    # Match filename with 12 hex digits before the extension
    # e.g. app.db8f2edc0c8a.js
    return re.match(r"^.+\.[0-9a-f]{8,12}\..+$", url)


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test
```

to your settings. 

So assuming I'm using the library correctly and we're not supposed to be using django's manifest for static files, I think we should add something to the settings to call this out

**Comment by MrBin99** [comment]
Hi,
If you use Whitenoise with django-vite and you don't want to use the manifest.json generated by Vite.
I think you shouldn't use django-vite at all because it will give you more pain to make it work as you want than using ViteJS directly. In my opinion.

**Comment by gone** [comment]
Yeah that makes sense to me - Use the manifest file generated by vite for vite files. I don't think you get anything out of trying to force which manifest file is used. 

Once those files are generated and put into the static folder, whitenoise is still going to serve them though - unless you're using a separate file server, which I think is sort of unusual on heroku/render/fly 

Would you be open to a documentation update to call this out?

**Comment by MrBin99** [comment]
Yeah of course. You can make a PR if you want (maybe in the "Notes" section, adding just a line to tell people).

**Comment by gone** [comment]
:+1:

**Comment by MrBin99** [comment]
Thanks again, I close the issue.
