### ISSUE TITLE
Web Worker Troubles

### ISSUE THREAD

**Issue by alexandermccormick** [MrBin99/django-vite#34]
I want to start by saying thanks for the work you've put into this, django-vite makes development a much smoother experience.

I was hoping to get some advice on implementing web workers with this. I think I might be missing something, as it seems like worker files not being served in developement.

I started testing this by creating a minimal vue app with vite, and everything worked as expected. From there I extended the django-vite-example to include this example, and at this point I am receiving the same error as in my project.

If you are curious at all, I've created a repo with the extended django-vite-example [here](https://github.com/alexandermccormick/django-vite-webworkers)

Was there any additional configuration to get web workers working with django-vite?

edit: Upon further investigation it seems this is due to the way Vite wraps worker files. The request for the intermediate `?worker_file` seems to be directed towards the same port as Django's server instead of the port Vite is listening on.

**Comment by MrBin99** [comment]
Hi thanks !

I'm sorry but I never used web workers, so I don't know how they work.
By reading the [doc](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), I suppose that they work like service workers.
If so, I think you need to have two different Javascript entry point for Vite (two bundles) : one for your `main.js` and one for your web worker `worker.js`.
You use `vite_asset` to import only the `main.js` and you use the [web worker api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#spawning_a_dedicated_worker) to import the other bundle.

I think it works like that 😀
