### ISSUE TITLE
DJANGO_VITE_STATIC_URL_PREFIX needs to include the trailing '/'

### ISSUE THREAD

**Issue by vaudric** [MrBin99/django-vite#36]
In v1.4
DJANGO_VITE_STATIC_URL = path_join(
    settings.STATIC_URL, DJANGO_VITE_STATIC_URL_PREFIX, ""
)

In v2.0
DJANGO_VITE_STATIC_URL = urljoin(
    settings.STATIC_URL, DJANGO_VITE_STATIC_URL_PREFIX
)

3rd agurment of urljoin is now missing => if DJANGO_VITE_STATIC_URL_PREFIX doesn't contain a trailing '/' it simply gets ignored

**Comment by MrBin99** [comment]
Thanks !

**Comment by vaudric** [comment]
You're most welcome. Thanks for building this neat module!

**Comment by vaudric** [comment]
Actually I mislead you to another bug. The functions path_join and urljoin don't have the same signature nor do they work the same way.

Here's a more verbose but solid solution inspired from: 

DJANGO_VITE_STATIC_URL = urljoin(
    settings.STATIC_URL, DJANGO_VITE_STATIC_URL_PREFIX
)
if not DJANGO_VITE_STATIC_URL.endswith('/'):
    DJANGO_VITE_STATIC_URL += '/'

**Comment by vaudric** [comment]
Excellent!
