### ISSUE TITLE
Dev Assets Not Loading

### ISSUE THREAD

**Issue by giantsoup** [MrBin99/django-vite#37]
I am attempting to use this with Vue.js and I have it all setup as instructed, however, when i run both Django and Vite servers my main.js file is being served at localhost:3000 and when i open my Django server at 127.0.0.1:8000 it is telling me that it can't find my main.js file even though (as far as i can tell) it is pointing to exactly where my main.js files lives.

I don't know what I'm doing wrong. I am new to both Django and Vite so maybe there is some fundamental piece of information I'm missing? Can you help me with this? What information should I provide that would help in troubleshooting?

I appreciate all the work you have put into this plugin, I would really like to get this working.

**Comment by giantsoup** [comment]
I tried using that example but it was too different from my setup, and there were things i noticed in there that were not explained in the README so I didn't understand why they were there.

I have looked at youtube videos and other repos and I think i am just too inexperienced to figure out what I am not understanding. If I sent you a link to my project where i have implemented this would you be able to look at it and see if anything obvious jumps out as the problem?

**Comment by MrBin99** [comment]
Of course send me the link.

**Comment by giantsoup** [comment]
I appreciate your willingness to help me out here. This is the link to my specific "vite-integration" branch: https://github.com/nootmuskaat/fine-ants/tree/vite-integration

When i run both the Django server and the Vite server I can see that the 8000 port Django url is trying to load my main.js file at this url "http://localhost:3000/static/src/js/main.js" which is exactly where that file is located. But it gives me a 404 saying that it can't find that file.

I am only trying to get my app to find that main.js file. I also want to figure out how to move over the css files and other bootstrap assets, so if you have any suggestions for that I would appreciate it. But for now I am just trying to get Vue working.

If you have any questions please let me know.

**Comment by MrBin99** [comment]
I'm sorry but I cannot find in your project Vite installed neither django-vite.

**Comment by giantsoup** [comment]
The Vite config is inside of the my frontend directory.

The settings.py file is inside of the fine_ants directory. And you can see that I have downloaded the django-vite plugin inside the poetry.lock file.

I think this is where I am getting confused because I don't have experience with all the different ways someone can setup a Django project, and I guess I have it setup differently than your example.

The idea is that my all of my frontend code is inside the frontend app, so the vite config is in there along with my source code in static/src. Then my index.html is inside of templates/frontend. That is how my friend recommended setting up the file structure since we will have a few different pages with different html templates that all include the index.html file.

**Comment by MrBin99** [comment]
I'm sorry but your repo seems not to be up to date. I cannot see anything related to Django Vite inside.

**Comment by giantsoup** [comment]
Thank you for trying.
