### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by thibaudcolas** [MrBin99/django-vite#4]
Just wanted to say I used Vite for the first time with this project, and it worked very well.

I wanted to suggest adding it to the awesome-vite’s "Integration with backends" list, as I imagine lots of other people would find it helpful: https://github.com/vitejs/awesome-vite#integrations-with-backends.

**Comment by MrBin99** [comment]
Thanks !
You're right, it might be helpful for some people. I will make a pull request on this repo.
