### ISSUE TITLE
Vite manifest sometimes blank

### ISSUE THREAD

**Issue by PetrDlouhy** [MrBin99/django-vite#40]
I am running `django-vite` on server, where it the `vite_asset` is present in 2 templates.
On those views I got approximately 1x an hour (after several thousands of requests) following error:
```
  File "django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "django/template/library.py", line 239, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "django/utils/safestring.py", line 47, in wrapped
    return safety_marker(func(*args, **kwargs))
  File "django_vite/templatetags/django_vite.py", line 453, in vite_asset
    return DjangoViteAssetLoader.instance().generate_vite_asset(path, **kwargs)
  File "django_vite/templatetags/django_vite.py", line 122, in generate_vite_asset
    raise RuntimeError(
RuntimeError: Cannot find src/comments/main.js in Vite manifest at /project/static/components/manifest.json
```

I tried to debug and found out, that the `self._manifest` is `None`.

My theory is, that is caused by two parallel requests creating an instance of `DjangoViteAssetLoader` at the same time.

**Comment by PetrDlouhy** [comment]
I am trying to implement this thread safe singleton solution: https://medium.com/analytics-vidhya/how-to-create-a-thread-safe-singleton-class-in-python-822e1170a7f6
in https://github.com/PetrDlouhy/django-vite/tree/debug_manifest
I will write more information and make MR when I finish testing of that.

**Comment by MrBin99** [comment]
Hi, thanks.
I've never imagined that something like this could happen.

**Comment by PetrDlouhy** [comment]
The fix with `threading.Lock()` didn't work, so either it doesn't work between requests or I am missing something.

**Comment by PetrDlouhy** [comment]
I was able to fix the problem in https://github.com/PetrDlouhy/django-vite/commit/649014be4caa3c4b4e0b850b5fdf2d318b5aea31

But I initialized the `_manifest` variable during the `django_vite.py` file loading.

It is worse approach, because I had to encapsulate the load in `try-catch` block, because it did run in management commands during project build, where the configuration was not complete.

This approach could mask important error messages, so I find it worse than the Singleton approach.
But I don't know how to fix the singleton correctly.

**Comment by MrBin99** [comment]
I was thinking, maybe do not touch the singleton class and force creating the instance when Django starts.
With this before handling any requests the singleton instance is created.

What do you think ?

**Comment by PetrDlouhy** [comment]
@MrBin99 I think, then it would degrade to the same solution as I made in https://github.com/PetrDlouhy/django-vite/commit/649014be4caa3c4b4e0b850b5fdf2d318b5aea31, except it would be complicated by the Singleton.

I realized, that I needed to catch the RuntimeError exception only because I was missing the manifest file in part of my build process and it was easy to fix that.

So I am suggesting to not use Singleton at all, if you agree that `manifest.json` must be present if user wants to run management commands such as `manage.py collectstatic`.

**Comment by MrBin99** [comment]
I don't understand why you think Singleton is not good in this situation. When I wrote the Singleton I was thinking not to read the manifest file at each request and keep it in memory as it's normally a tiny file and preserve IO access which can be slow (maybe not with the hardware of today).
The first request will read it but I wasn't thinking at all about concurrency.

My point is that this Singleton is read-only, you cannot and should not mutate it. So loading it when Django starts
in my mind should not make any problems and resolve your problem of concurrency ?

No ?

**Comment by PetrDlouhy** [comment]
I think, that technically both solutions will be the same. The manifest will be loaded to memory on Django start in both cases.

I don't see any benefit of Singleton in this case, but if you like that solution I will make MR with it.

**Comment by MrBin99** [comment]
I don't know, I think both of our solutions are viable. But in the end,
I think my solution modify less code than yourse. Not that I'm saying that your solution is better or worse than mine but you know the less code you change the less possibility of bugs you increase.

**Comment by PetrDlouhy** [comment]
@MrBin99 I have added PR with the fix and also fixed the pre-commit action.
Now it is deployed for few hours on our server and it seems running OK.

**Comment by MrBin99** [comment]
@PetrDlouhy It's OK for me.

**Comment by etienned** [comment]
Hi, do you think you will make a new release soon that will incorporate this fix? I'm hitting this problem. Thanks!
