### ISSUE TITLE
Possible urljoin issues with DJANGO_VITE_STATIC_URL_PREFIX

### ISSUE THREAD

**Issue by cmhobbs** [MrBin99/django-vite#44]
We're using s3 to host our assets and we set `DJANGO_VITE_STATIC_URL_PREFIX` in `settings.py` thusly:

`DJANGO_VITE_STATIC_URL_PREFIX =  f'https://{AWS_STORAGE_BUCKET_NAME}.s3.us-east-2.amazonaws.com/static/'`

In this case, the bucket name is "projectname-stage", so we end up with `https://projectname-stage.s3.us-east-2.amazonaws.com/static/" for our static url prefix.

We get a `RuntimeError` in django when visiting any page.  We suspect it's partially because a slash is missing from the scheme section of the url ("https:/" rather than "https://"):

`Cannot find src/index.js in Vite manifest at https:/projectname-stages3.us-east-2.amazonaws.com/static/manifest.json`

The runtime error references line 122 of `django_vite/templatetags/django_vite.py`.

Running various versions of our `DJANGO_VITE_STATIC_URL_PREFIX` through `urljoin` in a local python interpreter always includes both slashes after the scheme.  Somewhere along the line `DJANGO_VITE_MANIFEST_PATH` appears to be getting mangled.

Do we need to use a different variable or some different syntax to point to assets in s3?

**Comment by MrBin99** [comment]
Hi,

`DJANGO_VITE_STATIC_URL_PREFIX` was not designed to include full URL to an asset, this is the Django `STATIC_URL` (cf : [documentation](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-STATIC_URL)) variable you are looking for.
The `DJANGO_VITE_STATIC_URL_PREFIX` is use just after the `STATIC_URL` ([see here](https://github.com/MrBin99/django-vite/blob/master/django_vite/templatetags/django_vite.py#L67)).

**Comment by mrxsal** [comment]
Hi, I'm getting a similar error.
On Development everything works fine. Both with `DJANGO_VITE_DEV_MODE = true` or `DJANGO_VITE_DEV_MODE = false` and running `yarn build` and `manage.py collectstatic`
With the following settings:

STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
DJANGO_VITE_DEV_MODE = False
Error: `RuntimeError: Cannot find src/index.tsx in Vite manifest at /var/app/current/staticfiles/manifest.json`
For some reason it looks in the staticfiles folder but this folder doesn't exist on my server. the collected staticfiles are located in S3.

With explicitly setting `DJANGO_VITE_MANIFEST_PATH = STATIC_ROOT + "/manifest.json"`:
`RuntimeError: Cannot find src/index.tsx in Vite manifest at https://my-s3-static.s3.amazonaws.com/static/manifest.json`

This url definitely contains my manifest.json file, and it also includes the "src/index.tsx" key. (yes my manifest.json is in the root of the static folder)
