### ISSUE TITLE
Example Django + Vite app

### ISSUE THREAD

**Issue by mujahidfa** [MrBin99/django-vite#5]
Hi @MrBin99, first of all, appreciate your great work here!

I was wondering if you have an example repo that shows the usage of `django-vite` in a Django + Vite (+ Vue?) project? Personally I'm struggling to put the pieces together, so having an example project would greatly help. I can imagine for first-time users as well that it would be really helpful to see a project or to show best-practices for scaffolding a Django app with `django-vite`.

Thanks!

**Comment by MrBin99** [comment]
Hi,

Unfortunately, I don't have what you are looking for, I wrote only the documentation on the README file.
But tell me what you are struggling with ? I can maybe help you.

Is it from the Django side or from the ViteJS side ?

**Comment by MrBin99** [comment]
Oops sorry, missclick 😆

**Comment by mujahidfa** [comment]
Where would you typically put the Vite project in? Inside `/static`?

**Comment by MrBin99** [comment]
I put my assets (CSS, TS, ...) inside a `static/src` folder. At the root of the project I create my `vite.config.ts`.
I configure Vite to look for those files inside `static/src`.

For production :
I configure Vite to compile files in `static/src` into `static/dist`.
I include `static/dist` inside the `STATICFILES_DIRS` Django setting.
Then when I deploy my application, I run `python manage.py collectstatic` which include files in `static/dist` into Django
static file system [(Django doc)](https://docs.djangoproject.com/en/3.1/howto/static-files/deployment/#serving-static-files-in-production).

Hope I'm clear 😃

**Comment by sbadisa** [comment]
Thanks for the work on this package. I do agree a simple example project would be great. Some people (like me) learn best from examples.

**Comment by MrBin99** [comment]
Hi !

I've created an example project here [https://github.com/MrBin99/django-vite#example](https://github.com/MrBin99/django-vite#example).

Please tell me if it's helping you.

**Comment by mujahidfa** [comment]
FWIW, a year later, the example project is really helpful. Thanks @MrBin99!
