### ISSUE TITLE
Vite 3.0 no longer defaults to port 3000

### ISSUE THREAD

**Issue by samamorgan** [MrBin99/django-vite#51]
As of Vite 3.0, the dev server port is now 5173. Anyone on the latest versions must now add `DJANGO_VITE_DEV_SERVER_PORT = 5173` to their Django config.

**Comment by MrBin99** [comment]
Thanks for mentioning it !
I will not change the default for now because most of people using Django Vite use the 2.X version of Vite and I don't want to
break their code.
I will do it in the near future.

Thanks

**Comment by samamorgan** [comment]
Oh of course! I didn't make a PR for exactly this reason. I wouldn't want to see this changed without a bump to 3.x or a way to detect the configured Vite dev port. It's simple enough to change the setting, and I mostly wanted to stick this here for when others search out the issue.
