### ISSUE TITLE
Adding defer or async to css file

### ISSUE THREAD

**Issue by sanderese** [MrBin99/django-vite#58]
Hey there!

When building and using django-vite for production i'm unable to add a defer or async attribute to the css file that's being generated. 

I'm adding it to the javascript that I import like so:

`{% vite_asset 'page/main.js' defer="true" %}`

While that does add it to the javascript it does not do it to the css file. Am I able to configure this in any way?

Help is appreciated!

**Comment by thijskramer** [comment]
The attributes `async` and `defer` do not exist on `<link>` tags ([see the MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attributes)), so it is impossible to add those attributes.
