### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by guettli** [MrBin99/django-vite#6]
Are you sure you want to use the GPL License?

I must not use GPL software and many other developers have the same constraints.

**Comment by MrBin99** [comment]
Why not ?

**Comment by guettli** [comment]
The GPL is viral.

**Comment by MrBin99** [comment]
Can you be more specific ?

**Comment by muchzill4** [comment]
A bit late to the party. I think what @guettli meant was that the current license forces all users of your library to use GPL too. [This article seems to suggest as much](https://lukasa.co.uk/2012/05/GPL_vs_MIT_Which_License_To_Use/) also the [license conditions on GitHub](https://github.com/MrBin99/django-vite/blob/master/LICENSE).

**Comment by MrBin99** [comment]
Yeah I understand the problem, sorry but I'm not very aware of open source licensing.

I want to have a license that force developpers who makes changes on this lib that might be relevant to everybody to share it.
This is how I see open source. It doesn't matter if it's for a commercial product or not. But you are both right in the fact that I don't want to force people to use GPL back.

I will consider to change the license to maybe MIT or Apache 2.0.

Thanks.

**Comment by muchzill4** [comment]
@MrBin99 me either. 😉 Thanks for re-opening and looking into it.
