### ISSUE TITLE
Django + Vite Assistance

### ISSUE THREAD

**Issue by MarkovianPD** [MrBin99/django-vite#63]
I'm attempting to use Django + Vite and I'm not sure I completely understand this repository. I've followed the instructions just want to make sure I get everything and I'm doing it correctly. Does anyone have this setup correctly that can help me?

**Comment by nen2a** [comment]
if anyone did set it up correctly they are probably too busy and care too little to help anyone. 

it's not worth attempting to integrate vite with django with how complex it is, maybe if the instructions were better documented and there was less configuration. Hopefully one day django will have bundlers built in.

**Comment by robbyz512** [comment]
It's not complicated.

you can read the commits in example project to see exactly what to change
https://github.com/MrBin99/django-vite-example/commits/master

and in video below follow along during the parts where he sets up vite.
https://youtu.be/85-i4fr5MeU?t=137

**Comment by MarkovianPD** [comment]
> if anyone did set it up correctly they are probably too busy and care too little to help anyone.
> 
> it's not worth attempting to integrate vite with django with how complex it is, maybe if the instructions were better documented and there was less configuration. Hopefully one day django will have bundlers built in.

I've figured it out but thank you for your reply. It's unfortunate the minimal explanation going on in the GitHub here.

**Comment by thijskramer** [comment]
@MarkovianPD Good to hear that you've figured it out! Would you be interested in contributing by writing a better integration-explanation in the README?

**Comment by MarkovianPD** [comment]
@thijskramer Hello. I apologize that I didn't clarify any further but I didn't "figure it out" by using the repo I actually ended up going the route of linking the back-end and front-end with REST API.

**Comment by thijskramer** [comment]
Alright, that's an other way to connect both world :-) I'll close this issue then!
