### ISSUE TITLE
Looking for someone to maintain the project

### ISSUE THREAD

**Issue by MrBin99** [MrBin99/django-vite#70]
Hi,

I'm very sorry in advance for not merging your PRs nor responding to issues.
I cannot find time to maintain the project,

I'm looking for someone to tranfer the project or someone to fork the project and I will link his project in the README of his project
and mark this one as deprecated.

Thanks

**Comment by thijskramer** [comment]
@MrBin99 I'm happy to help with maintaining this project, or even fully take over the whole project.

**Comment by thijskramer** [comment]
@MrBin99 I'm happy to help with maintaining this package, and willing to receive a transfer of this project.

**Comment by MrBin99** [comment]
@thijskramer Cool thanks !

I've been thinking that perhaps I will just give you access to push and accept PRs in my place.
Changing repo will mostly break peoples that use the lib like myself 👀 

Is it OK for you to do it like that ?

**Comment by thijskramer** [comment]
Yes absolutely! That is even better :-)

**Comment by thijskramer** [comment]
@MrBin99 I'd like to change the default branch from `master` to `main` someday. Could I get a bit more permissions? Or can I notify you somehow when I'd like to to that?

**Comment by MrBin99** [comment]
Hi @thijskramer,

Sorry I didn't seen your messages.
Are you ok that I'll handoff the project to you ? It will be simpler to you for the future.

I will mark the repo on Pypi as "deprecated", and add a link to your repo.

It's ok for you ?

**Comment by thijskramer** [comment]
@MrBin99 Another enthusiast has popped up the last few months: @Niicck ! He'd like to be a maintainer as well. Could you give him the appropriate permissions?
