### ISSUE TITLE
Management commands error when DJANGO_VITE_DEV_MODE=False

### ISSUE THREAD

**Issue by ghickman** [MrBin99/django-vite#74]
In #41 an initial call to `DjangoViteAssetLoader.instance()` was added at the module level.  Because templatetags are imported on project boot this is firing when any management command is run.  With `DJANGO_VITE_DEV_MODE` set to False, as one would likely have in production or CI, the call is throwing an exception because the manifest file doesn't yet exist, but you're unable to create one because `collectstatic` also fails.

I've created a [minimal test case](https://github.com/ghickman/django-vite-repro) to show the bug in action.

Unless I've misunderstood how I should be configuring django-vite I think 2.1.0 is broken?

**Comment by thijskramer** [comment]
Yes you are absolutely right! Do you maybe have an idea how this could be fixed? Should we roll back #41? Or maybe initialize the Singleton in app_ready? 

I hope that I can find some time tomorrow to try a few solutions.

**Comment by thijskramer** [comment]
@ghickman what do you think of the solution I'm proposing in #75?

**Comment by ghickman** [comment]
@thijskramer – thanks for looking at this so quickly!

Your solution in #75 looks good, it's working for me with various management commands that don't need assets built 👍 

I don't think the check is firing though.  Testing with the repro repo I linked above, removing the pinned django-vite and pip installing your branch for #75 then running `python manage.py check --deploy` shows various warnings, but not the one from `check_loader_instance`.

**Comment by thijskramer** [comment]
that is because I've registered the check without `deploy=True`, and I think that it should stay that way. The check should occur not only in regard to production settings but to both development and production, if you'd ask me. What is your view on this?

**Comment by thijskramer** [comment]
I have released a fix yesterday as version 2.1.1.
