### ISSUE TITLE
Check for hashed version of manifest file

### ISSUE THREAD

**Issue by emab** [MrBin99/django-vite#79]
I'm having trouble getting this working on production - locally everything is fine.

The problems seem to stem because of my usage of Whitenoise and `CompressedManifestStaticFilesStorage`. 

If my understanding is correct, I should be able to use this alongside `django_vite` if I ensure the file names of any Vite generated files stay the same?

This is fine to achieve - but what I can't work out is how I'd find the vite manifest file with the hashed name? If I hard code a manifest path in `settings.py` it won't have the hash, and it won't use `staticfiles.json` to locate it.

Could this package introduce some setting that, if enabled, looks for `manifest.json` via the hashed staticfile name?

**Comment by emab** [comment]
I've managed to fix this by ensuring that files hashed by Vite are not hashed again by Whitenoise. I also do not hash the Vite manifest file, meaning the defined path is static.

**Comment by emab** [comment]
> /cc @emab - q.v this PR https://github.com/MrBin99/django-vite/pull/31 - the Vite files need to be identified by WN as immutable in order to have it set the correct cache-control header.

Ah so without that test was it not caching then properly at all? I was hoping that might have been done at the CDN level. Sorry about that!

**Comment by hugorodgerbrown** [comment]
np - I know where to send the AWS bill ;-)
