### ISSUE TITLE
Unable to use tags from django_vite with Jinja2

### ISSUE THREAD

**Issue by mbacalan** [MrBin99/django-vite#8]
Hello,

I followed everything in the readme and took a look at the example app too but I can't seem to get it working on our company project. Every tag registered by django_vite, such as `load`, `vite_hmr_client` etc. causes an `Encountered unknown tag` error. I can see the `django_vite` folder inside `venv` and it is present in `INSTALLED_APPS`. The server starts with no errors so it doesn't look like there's an issue with installing the pip package but when I load the page, it flips out.

We are using Jinja template engine via `django-jinja` package. I'm suspecting that's the cause?

Django Version: | 2.2.24
-- | --
Python Version: | 3.9.5

Let me know if you need more information about the project.

Thanks.

**Comment by MrBin99** [comment]
Hi,
I'm sorry but django-vite does not support Jinja templating for the moment.
I keep this issue open to maybe add the feature if other people are interested too.
Or feel free to do a PR.

**Comment by wizpig64** [comment]
Hi @mbacalan,

django-jinja automatically loads django's built-in tags, but it has to be configured to load any third-party tags in your settings, like this:

```python
# settings.py

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "OPTIONS": {
            "globals": {
                "vite_hmr_client": "django_vite.templatetags.django_vite.vite_hmr_client",
                "vite_asset": "django_vite.templatetags.django_vite.vite_asset",
            },
            ...
```

Furthermore, in jinja templates, you call the tags as if they were functions, with ``{{ }}`` not `{% %}`. So if you have a django template like this:

```html
{% load django_vite %}
<html>
<head>
  <title>vite on django</title>
  {% vite_hmr_client %}
</head>
<body>
  <div id="app"></div>
  {% vite_asset 'src/main.js' %}
</body>
</html>
```

...you would need to convert it to this in a jinja template:

```html
<html>
<head>
  <title>vite on jinja</title>
  {{ vite_hmr_client() }}
</head>
<body>
  <div id="app"></div>
  {{ vite_asset('src/main.js') }}
</body>
</html>
```

I hope that helps.

**Comment by mbacalan** [comment]
@wizpig64 thanks! Works like a charm. Maybe this issue can be closed, unless this is only applicable to `django-jinja` and using Jinja2 in a different way would still require changes.

**Comment by MrBin99** [comment]
Thanks for your help @wizpig64 !
@mbacalan I let you close this issue, if it's good for you.

**Comment by sondrelg** [comment]
This was very helpful. I think adding it to the readme would be a good idea 🙂
