### ISSUE TITLE
About caching using whitenoise package

### ISSUE THREAD

**Issue by oussama-he** [MrBin99/django-vite#93]
According to the [note](https://github.com/MrBin99/django-vite#notes) about caching static files when serving them using the whitenoise package, you said that we should change the `WHITENOISE_IMMUTABLE_FILE_TEST` setting to consider the files generated by VITEJS to be cached.

But when looking at the regex it looks like it doesn't match the files generated by VITEJS because they are of this format: `file-[hash].extname`, where the separator between the file name and the hash is `-` not a period and the `hash` is 8 hexadecimal digits.

I'm missing a point or something is wrong?

**Comment by Niicck** [comment]
You are correct!

The regex in the note `{8,12}` does handle the case of 8 digits (and 12 digits, to not break compatibility with Django's ManifestStaticFilesStorage). But you're correct that it's not accounting for a `-` separator. So the actual working regex should be:

`^.+[\.\-][0-9a-f]{8,12}\..+$`

Good catch!
